[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "RECON"
authors = [{name = "MU-Enigma", email = "enigma@mahindrauniversity.edu.in"}]
dynamic = ["version", "description"]
